# Generated by Django 4.1.2 on 2022-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('SELF-CARE', 'SELF-CARE'), ('HEALTH-AND-FITNESS', 'HEALTH-AND-FITNESS'), ('CAFES-AND-RESTAURANTS', 'CAFES-AND-RESTAURANTS'), ('CAR', 'CAR'), ('EDUCATION', 'EDUCATION'), ('LEISURE-AND-ENTERTAINMENT', 'LEISURE-AND-ENTERTAINMENT'), ('PAYMENTS-COMMISSIONS', 'PAYMENTS-COMMISSIONS'), ('SHOPPING', 'SHOPPING')], max_length=255),
        ),
    ]
